sc:
  rest-template:
    connect-timeout: 20000
    response-timeout: 20000
  backend:
    baseUrl: http://localhost:8088

server:
  port: 80

zk:
  resource-uri: /zkres
  zul-view-resolver-prefix: /
