sc:
  rest-template:
    connect-timeout: 20000
    response-timeout: 20000
  update:
    enable: false

server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/ilya/sc2stats_db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
